### ISSUE TITLE
Daily overview report

### ISSUE THREAD

**Issue by swa-ds** [doubleSlashde/KeepTime#123]
I would like to have a report with a daily overview, that shows the following for every project:

- Project name
- total duration of the project for the currently viewed day, and 
- all notes that were entered for the project on this day (separated by semicolon) 

For example:

| Project | Total duration | Notes |  | 
|--------|-----------------|-------|--|
| Idle | 1:16:42 | (no notes) | (Copy Notes) |
| Rüstzeiten | 0:27:23 | Softwareupdates (Barracuda); Rechnerneustart; Feature-Request für KeepTime eingestellt | (Copy Notes) |
| Project X | 7:52:11 | Abstimmungen; Story 1; Story 2 | (Copy Notes) |
| ... | ... | ... |  (Copy Notes) |

Additionally, a button at the end of each column to copy the notes would be great.

**Comment by Death111** [comment]
Hi @swa-ds,
we did implement #119 feature. With this the UI basically already looks like your requested feature (in collapsed mode):
Difference is that no "notes" are shown:
![image](https://user-images.githubusercontent.com/5772511/212687408-516c9e2a-2831-4846-8c44-8b3d01a843e5.png)

I assume with #119 we could close this issue? Let me know what you think ;)

**Comment by swa-ds** [comment]
Yes, thank you. That's fine for me!
