### ISSUE TITLE
Minimize KeepTime when clicking on "x"

### ISSUE THREAD

**Issue by swa-ds** [doubleSlashde/KeepTime#151]
Several times it happend that I closed KeepTime accidentally by clicking on the "x" in the upper left corner. 

I would welcome a functionality that just minimizes the program to the symbol tray, instead of closing it, as e.g. MS Teams does. The program can be closed via a right click on the symbol and selecting "Exit" in the context menu that then apeears. 

The functionality could be optional, with the possibility to activate it in the configuration dialog.

**Comment by Death111** [comment]
@swa-ds there is a "confirm on close" setting which you can activate in the settings. so at least you won't close it on accident.

Currently I do not plan to add a tray icon. If the confirm-function is sufficient for you, feel free to close the issue. If not we can keep it open ;)

**Comment by swa-ds** [comment]
Thanks for the hint regarding the "confirm close" option. This is sufficient for me.
