### ISSUE TITLE
add time to project

### ISSUE THREAD

**Issue by mplieske** [doubleSlashde/KeepTime#28]
Often I forget to start keeptime to late or do not start the computer when start working. So it would be nice to have the possibility to add time to specific projects.

**Comment by Death111** [comment]
Did not consider this, as I didn't want to have projects overlapping. Logic to prevent overlaps seemed to be to difficult.
Not considering overlaps (just do what the user sets) could be an option.

**Comment by Death111** [comment]
Implemented with #42
