### ISSUE TITLE
Opening report > 1 time in a row results in warnings

### ISSUE THREAD

**Issue by Death111** [doubleSlashde/KeepTime#55]
1. Click report button
1. Close report
1. Click report button
1. look at logs

Logs contain entries like:
22:55:29.126 [JavaFX Application Thread] WARN  javafx.css - Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '*.button' in stylesheet jar:file:/*path to javahome*/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss

think this was introduced with the treeview control

**Comment by JSchraff** [comment]
known bug in java 8
https://bugs.openjdk.java.net/browse/JDK-8182152
but no intention to resolve

**Comment by JSchraff** [comment]
opening 3rd time no buttons visible,
looking for workaround

**Comment by Death111** [comment]
Fixed with #61
