### ISSUE TITLE
Notes do not wrap correctly in report

### ISSUE THREAD

**Issue by Death111** [doubleSlashde/KeepTime#57]
The notes in the report view do not wrap in most cases.

Also, sometimes they overlap each other.. I think this is related to the dialog.css -fx-cell-size.

**Comment by JSchraff** [comment]
cant set -fx-cell-size smaller than 24(default) without triggering this bug and cant find other working solution to make rows smaller

**Comment by Death111** [comment]
yes, seems to be not so easy to do. maybe we should not wrap it for the time we have no solution, as it may make the report not usable sometimes, when the notes start overlapping each other.

**Comment by Death111** [comment]
Fixed with #76 by disabeling wrapping.
