### ISSUE TITLE
current work visible in report but changes get discarded 

### ISSUE THREAD

**Issue by JSchraff** [doubleSlashde/KeepTime#85]
the current work is visible in the report after the first time the autosave is run. then it is possible to edit it which will be done.
But on the next autosave the changes get overwritten, because the activeWorkItem isn't getting updated.

Proposed Solutions:
1. remove the active Work Item from the Report, so it cannot be changed.
2. update the activeWorkItem if the workitem gets changed.

**Comment by swa-ds** [comment]
I vote for option 2 (if feasible), because sometimes I want to enter notes directly after I switched to a new project.
