### ISSUE TITLE
Symbol/Logo for application

### ISSUE THREAD

**Issue by mplieske** [doubleSlashde/KeepTime#89]
A logo or something along those lines would be greate. I would set the symbol of a link to the batch file to this logo so it looks nicer if I search for KeepTime :)

**Comment by mplieske** [comment]
This does not look so nice ^^
![image](https://user-images.githubusercontent.com/43209805/147889097-68c4835c-a19c-456e-a4ff-5ef6baee0bc6.png)

**Comment by Death111** [comment]
Hey @mplieske,
I agree. An issue already exists for this #20. I will add your hint with the batch file.

**Comment by mplieske** [comment]
Nice 👍
