### ISSUE TITLE
Only ask for notes when changing from work items

### ISSUE THREAD

**Issue by sgiessmann** [doubleSlashde/KeepTime#92]
As a user, I want the reminder pop-up for notes only to show if I am switching from an item that is marked as 'work'. This on the one hand prevents me from missing the pop-up and my work hours not being tracked, and on the other hand doesn't "teach" me the automatism to close the pop-up without entering notes.

Current situation:
When the notification for missing notes is active, it pops up every time when changing work items (without comment) regardless if the task was marked as isWork or not. For  example: Setting to Idle for lunch -> returning and switching to a work item -> pop-up asks for a note what has been done in the none work item Idle.

Target situation:
The notification is only shown when switching away from a work task that has no notes.

Optional:
This behavior is configurable.

**Comment by Death111** [comment]
@sgiessmann the feature was implemented with the optional behavior. feel free to verify it on develop branch. If happy you may close the enhancement request.
