### ISSUE TITLE
Confirmation dialog on closing application

### ISSUE THREAD

**Issue by PhiGegner** [doubleSlashde/KeepTime#93]
Sometimes I accidentally close KeepTime. To prevent this from happening, I want to have a confirmation dialog whether I really want to close the application.

Optional: Add a setting to enable/disable the dialog.

**Comment by Death111** [comment]
@PhiGegner the feature was implemented with the optional setting. feel free to verify it on develop branch. If happy you may close the enhancement request.

**Comment by PhiGegner** [comment]
Tested it and it works fine.
